[package]
name = "docker-desktop"
version = "0.1.0"
authors = ["Dan Knox <dknox@coinstackcard.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
